const Languages = {
    en: {
        'Submit': 'Submit',
        'Empty List': 'Empty List',
        'What are you looking for?': 'What are you looking for?',
        'See All': 'See All',
        'Browser By Category': 'Browser By Category',
        'Brands': 'Brands',
        'Free Shipping': 'Free Shipping',
        'Quantity': 'Quantity',
        'Total': 'Total',
        'Checkout': 'Checkout',
        'My Orders': 'My Orders',
        'My WishList': 'My WishList',
        'Yours': 'Yours',
        'My Address Book': 'My Address Book',
        'New Feeds': 'New Feeds',
        'Add to Cart': 'Add to Cart',
        'Results': 'Results',
        'Result': 'Result',
        'Change Language': 'Change Language',
        'Rate App': 'Rate App',
        'Share App': 'Share App',
        "Can not connect to server": "Can not connect to server.",
        'Sponsored': 'Sponsored',
        "Category": "Category",
        "Price Range": "Price Range",
        "Brand": "Brand",
        "Feedback": 'Feedback',
        'Email': 'Email',
        'Password': 'Password',
        'RePassword': 'Confirm Password',
        'Sign In': 'Sign In',
        'Sign Up': 'Sign Up',
        'Do you have account with HiKids?': 'Do you have account with HiKids?',
        'First Name': 'First Name',
        'Profile': 'Profile',
        'Full Name': 'Full Name',
        'Last Name': 'Last Name',
        'Successfully': 'Successfully',
        'Telephone': 'Telephone',
        'Street': 'Street',
        'City': 'City',
        'Postcode': 'Postcode',
        'Choose Country': 'Choose Country',
        'Shipping Methods': 'Shipping Methods',
        'Please choose shipping method': 'Please choose shipping method.',
        'Please input all fields': 'Please input all fields',
        'Please login first': 'Please login first',
        'Payment Methods': 'Payment Methods',
        'Sign Out': 'Sign Out',
        'Add Address': 'Add Address',
        'Choose Region': 'Choose Region',
        'Status': 'Status',
        'Created': 'Created',
        'Code': 'Code',
        'new arrivals': 'New Arrivals',
        'Sign': 'Sign In',
        'Create New Account': 'Create New Account',
        'Credit card': 'Credit card',
        'Card Expiration Date': 'Card Expiratory date',
        'Address': 'Address',
        'Do You Have An Account?': "Do You Have An Account?",
        'home': 'Home',
        'categories': 'Categories',
        'cart': 'Cart',
        'carts': 'Cart',
        'branches': 'Branches',
        'other': 'Other',
        'Add to Wishlist': 'Add to Wishlist',
        'description': 'Description',
        'Delete': 'Delete',
        'Mobile': 'Mobile',
        'The Confirm Password is not matched': 'The Confirm Password is not matched',
        'products': 'Products',
        'settings': 'Settings',
        'about': 'About',
        'Best Selling': 'Best Selling',
        'Shop by Characters': 'Characters',
        'Shop by':'Shop by',
        'conditions': 'Conditions and terms',
        'offers': 'Offers',
        'Special': 'Special',
        'discounts': 'Discounts',
        'packaging Choices': 'Packaging Choices',
        'Items number': 'Items Count',
        'taxes': 'Taxes',
        'shipping': 'Shipping',
        'Items price': 'Items price',
        'Request Details': 'Request Details',
        'Carton box': 'Carton box',
        'Plastic': 'Plastic bags',
        'Wooden boxes': 'Wooden boxes',
        'please choose proper packaging': 'Please Choose Suitable Packaging',
        'Not Available': 'Not Available',
        'all': 'All',
        'Contact us': 'Contact us',
        'product Info': 'Product Information',
        'Have problem or question': 'Have problem or question',
        'Search in all categories': 'Search in all categories',
        'Not have what you want': 'You did not found what you want',
        'My Profile': 'My Profile',
        'Contact Info': 'Contact Info',
        'edit': 'edit',
        'name': "Name",
        'mobile': 'Mobile No.',
        'Order Address': 'Order Address',
        'district': 'District',
        'Language': "Language",
        'save': "Save",
        'total':'Total',
        'Arka destrict':'Arka destrict',
        'Al-Alia destrict' : 'Al-Alia destrict',
        'Al-Malk Fahd destrict' : 'Al-Malk Fahd destrict',
        'Al-Haramaa destrict' : 'Al-Haramaa destrict',
        'Al-Waha destrict' : 'Al-Waha destrict',
        'Order Id': "Order Id",
        'Total Sum': 'Total Sum',
        'Categories Count': 'Items Number',
        'Date': 'Date',
        'delivered': "delivered",
        'Order Details': 'Order Details',
        'Cancel Order': 'Cancel Order',
        'Shipment Address': 'Shipment Address',
        'District': 'District',
        'About Us': 'About Us',
        'terms and conditions': 'terms and conditions',
        'Details':'Details',
        'Related Products':'Related Products',
        'Add a comment':'Add a comment',
        'Example: add a package':'Example: add a package',
        'Order Status':'Order Status',
        'Being Prepared':'Being Prepared',
        'Packaging Choice':'Packaging Choice',
        'Not Found':'Not Found',
        'Payment Method':'Payment Method',
        'Submit Order':'Submit Order',
        'Payment Information':'Payment Information',
        "advanced search": "Advanced Search",
        'age': 'Age',
        'gender': "Gender",
        'price': 'Price',
        'cancel filter': 'Cancel Filter',
        'character': "Character",
        'option': 'option',
        'Not Available Info': 'Not Available',
        'Confirm Payment':'Confirm Payment',
        'Country':'Country',
        'Privacy Policy':'Privacy Policy',
        'Delivery info':'Delivery Info',
        'Branches List':'Branches List',
        'Branches on Map':'Branches on Map',
        'No items found':'No items found',
        'Notes':'Notes',
        'SAR':'SAR',
        'Confirm Cancel':'Confirm Cancel',
        'Add All to Cart':'Add All to Cart',
        'Region':'Region',
        'about us content': {
            "_1": "- هاي كيدز أول سوبرماركت يعتني بالطفل في المملكة العربية السعودية, استغرق تكوين فكرة و هوية المشروع مايقارب الـ 17 شهر, وبفضل الله تم إطلاق اول فروع سلسة هاي كيدز في عام 2012 .",
            "_2": "- شعارنا هو أطفالنا نجوم مفعمين بالحيوية والنشاط والمرح, ولنحقق لكم ذلك حرصنا على تقديم كل ماهو جديد ورائع في عالم الألعــاب والحلويات.",
            "_3": "- هدفنا ان نكون الشركة الأولى في ترفيه حياة الأطفال, وخلق علامة تجارية محلية بمواصفات عالمية.",
            "_4": "- يقوم سوبرماركت Hi Kids على 3 أقسام:",
            "_5": "1- قسم الالعاب و المنتجات الترفيهية والتعليمية التي من شأنها دعم المهارات الحركية و الحسية والأدراكية وتنشيط الذهـــن والأبتعاد قـــدر الأمكان عن الألعاب الألكترونية التي تقلل من الحركة.",
            "_6": "2- قسم الأطعمة والحلويات حيث نقدم فيه نخبة مختارة من أحدث المنتجات بالأضافة للمنتجات الكلاسيكية مع الابتعاد عن بعض المنـــتجات الضارة كالمشروبات الغازية.",
            "_7": "3- قسم منتجات العناية بالأم و صيدلية الطفل والتي تم اختيارها بعناية.",
        },
        'privacy policy': {
            "_1": 'الخصوصية وبيان سريّة المعلومات: نحن على علم بمسؤوليتنا تجاه حماية معلوماتك الشخصية ونأخذ هذا الأمر بجدية تامة. ونحن نعتقد أن معلوماتك الشخصية هي واحدة من أهم الموراد لدينا. نقدر مخاوفكم واهتمامكم بشأن خصوصية بياناتكم على شبكة الإنترنت. فجميع المعلومات الي تقدمها لنا هي بيانات محمية ولا يقوم بالاطلاع عليها إلا للأشخاص المخولين لذلك بموجب عملهم وفقاً لبنود حماية الخصوصية. لقد تم إعداد هذه السياسة لمساعدتكم في تفهم طبيعة البيانات التي نقوم بتجميعها منكم عند زيارتكم لموقعنا على شبكة الانترنت وكيفية تعاملنا مع هذه البيانات الشخصية.',
            "_2": 'التصفح : لم نقم بتصميم هذا الموقع من أجل تجميع بياناتك الشخصية من جهاز الكمبيوتر الخاص بك أثناء تصفحك لهذا الموقع, وإنما سيتم فقط استخدام البيانات المقدمة من قبلك بمعرفتك ومحض إرادتك.',
            "_3": 'عنوان بروتوكول شبكة الإنترنت (IP) : في أي وقت تزور فيه اي موقع انترنت بما فيها هذا الموقع , سيقوم السيرفر المضيف بتسجيل عنوان بروتوكول شبكة الإنترنت (IP) الخاص بك , تاريخ ووقت الزيارة ونوع متصفح الإنترنت الذي تستخدمه والعنوان URL الخاص بأي موقع من مواقع الإنترنت التي تقوم بإحالتك إلى الى هذا الموقع على الشبكة.',
            "_4": 'إفشاء المعلومات : سنحافظ في كافة الأوقات على خصوصية وسرية كافة البيانات الشخصية التي نتحصل عليها. ولن يتم إفشاء هذه المعلومات إلا إذا كان ذلك مطلوباً بموجب أي قانون أو عندما نعتقد بحسن نية أن مثل هذا الإجراء سيكون مطلوباً أو مرغوباً فيه للتمشي مع القانون , أو للدفاع عن أو حماية حقوق الملكية الخاصة بهذا الموقع أو الجهات المستفيدة منه.',
            "_5": 'البيانات اللازمة لتنفيذ المعاملات المطلوبة من قبلك: عندما نحتاج إلى أية بيانات خاصة بك , فإننا سنطلب منك تقديمها بمحض إرادتك. حيث ستساعدنا هذه المعلومات في الاتصال بك وتنفيذ طلباتك حيثما كان ذلك ممكنناً. لن يتم اطلاقاً بيع البيانات المقدمة من قبلك إلى أي طرف ثال بغرض تسويقها لمصلحته الخاصة دون الحصول على موافقتك المسبقة والمكتوبة ما لم يتم ذلك على أساس أنها ضمن بيانات جماعية تستخدم للأغراض الإحصائية والأبحاث دون اشتمالها على أية بيانات من الممكن استخدامها للتعريف بك.',
            "_6": 'عند الاتصال بنا : سيتم التعامل مع كافة البيانات المقدمة من قبلك على أساس أنها سرية . تتطلب النماذج التي يتم تقديمها مباشرة على الشبكة تقديم البيانات التي ستساعدنا في تحسين موقعنا.سيتم استخدام البيانات التي يتم تقديمها من قبلك في الرد على كافة استفساراتك , ملاحظاتك , أو طلباتك من قبل هذا الموقع أو أيا من المواقع التابعة له .',
            "_7": 'إفشاء المعلومات لأي طرف ثالث : لن نقوم ببيع , المتاجرة , تأجير , أو إفشاء أية معلومات لمصلحة أي طرف ثالث خارج هذا الموقع, أو المواقع التابعة له.وسيتم الكشف عن المعلومات فقط في حالة صدور أمر بذلك من قبل أي سلطة قضائية أو تنظيمية.',
            "_8": 'التعديلات على سياسة سرية وخصوصية المعلومات : نحتفظ بالحق في تعديل بنود وشروط سياسة سرية وخصوصية المعلومات إن لزم الأمر ومتى كان ذلك ملائماً. سيتم تنفيذ التعديلات هنا او على صفحة سياسة الخصوصية الرئيسية وسيتم بصفة مستمرة إخطارك بالبيانات التي حصلنا عليها , وكيف سنستخدمها والجهة التي سنقوم بتزويدها بهذه البيانات.',
            "_9": 'الاتصال بنا: يمكنكم الاتصال بنا عند الحاجة من خلال الضغط على رابط اتصل بنا المتوفر في روابط موقعنا',
            "_10": 'اخيرا إن مخاوفك واهتمامك بشأن سرية وخصوصية البيانات تعتبر مسألة في غاية الأهمية بالنسبة لنا. نحن نأمل أن يتم تحقيق ذلك من خلال هذه السياسة.',
        },
        'delivery info': {
            '_1': 'مدة الشحن و التوصيل :',
            '_2': '- بالنسبه للتوصيل المحلي: داخل المملكة تستغرق مدة الشحن غالباً من 24 ساعه إلى 7ايام عمل و قيمة التوصيل 25 ريال داخل الرياض و 50 ريال لاي منطقة اخرى داخل المملكة.',
            '_3': '- بالنسبه للتوصيل الدولي: خارج المملكة فإن مدة وقيمة الشحن تختلف بحسب الدولة التي سوف يتم الشحن إليها, كل ماعليكم لمعرفة التكاليف والوقت ارسال ايميل لنا بالأصناف التي ترغبون بها و الكميات مع بياناتكم شاملة (الاسم- العنوان- رقم الجوال) وسيتم الرد عليكم بأقرب فرصة واعلامكم بطريقة الدفع المناسبة لأيصال طلبكم, الايميل لاستقبال طلباتكم من خارج المملكة:customers_service@hikids.com.sa.',
            '_4': 'ملاحظة: سوف تقوم الشركة الناقلة بالإتصال بكم لترتيب عملية استلام المنتج.'
        },
        'pay upon delivery':'Pay upon delivery (Riyadh only)',
        'Bank transfer':'Bank transfer',
        'Credit Card':'Credit Card (Visa, Mastercard)',
        'Money Account':'Money Account',
        'SADAD':'SADAD',
        'Pickup from store':'Pickup from store (Riyadh only)',
        'Order Created Successfully':'Order Created Successfully',
        'An_Error_Occured' :'An Error Occured, Try Later',
        'Help':'Help',
        'canceled':'Canceled',
        'closed':'Closed',
        'completed':'Completed',
        'onhold':'OnHold',
        'pending':'Pending',
        'pending payPal':'Pending PayPal',
        'pending_payPal':'Pending PayPal',
        'pending payment':'Pending Payment',
        'pending_payment':'Pending Payment',
        'processing':'Processing',
        'complete': 'Completed',
        'payfort failed':'Payfort failed',
        'payfort_failed':'Payfort failed',
        'payfort_fort_new':'Payfort New Order',
        'payfort_fort_cc': 'Payfort Credit Card',
        'paypal canceled reversed':'PayPal Canceled Reversal',
        'paypal_canceled_reversed':'PayPal Canceled Reversal',
        'suspected_fraud':'Suspected Fraud',
        'paypal reversed':'PayPal Reversed',
        'paypal_reversed':'PayPal Reversed',
        'Are you sure to cancel this order?':'Are you sure to cancel this order?',
        'Cancel':'Cancel',
        'Confirm Delete': 'Confirm Delete',
        'Are you sure to delete':'Are you sure to delete this item?',
        'Confirm':'Confirm',
        'cashondelivery':'Cash on Delivery',
        'ContactAddress':'Address: Localizer Mall, Riyadh',
        'Registered Successfully':'Registered Successfully',
        'Added to cart':'Added to cart',
        'Added to wishlist':'Added to your wish list',
        'Signed out successfully':'Signed out successfully',
        'IBAN number':'IBAN no: SA18 8000 0504 6080 1003 1954',
        'Account number':'Account no: 504608010031954',
        'After bank transfer':'Please send copy of transfer transaction to this number on watsapp : 0501217999',
        'We will communicate with you for details':'Send your order through email (sales@yourcompany.com) and We will communicate with you for details',
        'With option for free delivery inside Riyadh only':'With a free delivery feature if the total cost reaches a certain value controlled by us or before you (Inside Riyadh Only)',
        'Extra Charges':'This product has extra shipping outside Riyadh of value: ',
        'banktransfer':'Bank Transfer',
        'payfort_fort_sadad':'SADAD',
        'Item Name':'Product Name',
        'Mash`al ebn Abd-elAziz, besides Al-Danoob ': 'Mash`al ebn Abd-elAziz, besides Al-Danoob ',
        'Waseel Center, Khalid Ibn Al Walid Street, Al Hamra, 13216':'Waseel Center, Khalid Ibn Al Walid Street, Al Hamra, 13216',
        '7004 King Abdul Aziz Branch Rd, King Fahd, 4500':'7004 King Abdul Aziz Branch Rd, King Fahd, 4500',
        'King Abdullah Rd, King Abdullah, Riyadh 12451, Saudi Arabia':'King Abdullah Rd, King Abdullah, Riyadh 12451, Saudi Arabia',
        'Riyadh, Tahlia, Localizer Mall': 'Riyadh, Tahlia, Localizer Mall',
        'Watsapp:':'Watsapp:',
        'Unifed No:':'Unifed No:',
        'Email:':'Email:',
        'Cancel Payment':'Cancel Payment',
        ' Are you sure to cancel payment?':' Are you sure to cancel payment?',
        'Our Dear Customers':'Our Dear Customers, Our pleasure to help you through the following ways',
        'Product isnot available':'The product isn\'t available now,Try search by another words or contact us for help:',
        'Categories arenot available': 'There is no subcategories available now',
        'Cart is empty': 'Cart is empty'
    }
    , ar: {
        'Submit': 'ارسال',
        'Empty List': 'القائمة فارغة',
        'What are you looking for?': 'إبحث هنا',
        'See All': 'مشاهدة الجميع',
        'Browser By Category': 'تصفح القائمة',
        'Brands': 'علامة تجارية',
        'Free Shipping': 'شحن مجاني',
        'Quantity': 'الكمية',
        'Total': 'اجمالي الطلب',
        'Checkout': 'المحاسبة',
        'My Orders': 'الطلبات',
        'My WishList': 'المفضلة',
        'Yours': 'خاصة لك',
        'My Address Book': 'عنواني',
        'New Feeds': 'الجديد',
        'Add to Cart': 'اضف الى السلة',
        'Add All to Cart': 'اضافة الكل الى السلة',
        'Results': 'النتائج',
        'Result': 'النتيجة',
        'Change Language': 'تغيير اللغة',
        'Rate App': 'قيم البرنامج',
        'Share App': 'ارسل التطبيق ',
        "Can not connect to server": "لا يمكن الاتصال بالخادم",
        'Sponsored': 'برعاية',
        "Category": "القوائم",
        "Price Range": "السعر بين",
        "Brand": "العلامة التجارية",
        "Feedback": 'الرد',
        'Email': 'البريد الإلكتروني',
        'Password': 'كلمة المرور',
        'RePassword': 'تأكيد كلمة المرور',
        'Sign In': 'تسجيل الدخول',
        'Sign': 'دخول',
        'Sign Up': 'تسجيل',
        'Do you have account with HiKids?': 'هل يوجد عندك حساب معنا ؟',
        'Create New Account': 'انشاء حساب جديد',
        'First Name': 'الاسم الأول',
        'Profile': 'حسابى',
        'Full Name': 'الاسم بالكامل',
        'Last Name': 'الاسم اأخير',
        'Successfully': 'بنجاح',
        'Telephone': 'الهاتف',
        'Street': 'الشارع',
        'Postcode': 'الرمز البريدي',
        'Choose Country': 'اختر الدولة',
        'Shipping Methods': 'طريقة التوصيل',
        'Please choose shipping method': 'من فضلك اختر طريقة التوصيل',
        'Please input all fields': 'يرجي ملئ كافة الحقول',
        'Please login first': 'يرجى تسجيل الدخول',
        'Payment Methods': 'طريقة الدفع',
        'Sign Out': 'تسجيل الخروج',
        'Add Address': 'اضف عنوان',
        'Choose Region': 'اختر المنطقة',
        'Status': 'الحالة',
        'Created': 'تم الانشاء',
        'Code': 'الكود',
        'new arrivals': 'وصل حديثاً',
        'Credit card': 'رقم البطاقة الإئتمانية',
        'Card Expiration Date': 'تاريخ انتهاء البطاقة',
        'Address': 'العنوان',
        'Do You Have An Account?': "هل لديك حساب بالفعل؟",
        'home': 'الرئيسية',
        'categories': 'الأقسام',
        'cart': 'السلة',
        'branches': 'الفروع',
        'other': 'اخرى',
        'Add to Wishlist': 'اضف الى المفضله',
        'description': 'الوصف',
        'Delete': 'حذف',
        'Mobile': 'رقم الجوال',
        'The Confirm Password is not matched': 'تأكيد كلمة المرور غير مطابقة',
        'products': 'منتجات',
        'settings': 'الإعدادات',
        'about': 'عن هاي كيدز',
        'Best Selling': 'الأكثر مبيعاً',
        'Shop by Characters': 'تسوق حسب الشخصية',
        'Shop by':'تسوق حسب ',
        'conditions': 'الشروط والاحكام',
        'offers': 'العروض',
        'Special': 'مميز',
        'carts': 'سلة المشتريات',
        'discounts': 'اسعار قيمة',
        'packaging Choices': 'خيارات التغليف',
        'Items number': 'عدد الأصناف',
        'taxes': 'الضريبة',
        'Items price': 'القيمة الجزئية',
        'shipping': 'الشحن',
        'Request Details': 'تفاصيل الطلب',
        'Carton box': 'صناديق كرتون',
        'Plastic': 'غلاف بلاستيك',
        'Wooden boxes': 'صناديق خشبية',
        'please choose proper packaging': 'الرجاء اختيار التغليف المناسب',
        'Not Available': 'غير متاح',
        'all': 'الكل',
        'Contact us': 'تواصل معنا',
        'product Info': 'معلومات المنتج',
        'Have problem or question': 'لديك مشكلة في الطلب أو استفسار',
        'Search in all categories': 'إبحث في كل الأقسام',
        'Not have what you want': 'لم تجد ما تبحث عنه',
        'My Profile': 'حسابى',
        'Contact Info': 'بيانات الإتصال',
        'edit': "تعديل",
        'name': "الإسم",
        'mobile': 'رقم الجوال',
        'Country':'البلد',
        'City': 'المدينة',
        'Order Address': 'عنوان الشحن',
        'district': "الحى",
        'Language': "اللغه",
        'save': "حفظ",
        'Arka destrict':'حي العرقة',
        'Al-Alia destrict':'حي العليا',
        'Al-Malk Fahd destrict':'حي الملك فهد',
        'Al-Haramaa destrict':'حي الحمراء',
        'Al-Waha destrict': 'حي الواحة',
        'Order Id': "رقم الطلب",
        'Total Sum': 'المبلغ الاجمالى',
        'Categories Count': 'عدد الأصناف',
        'Date': 'تاريخ الطلب',
        'delivered': 'تم التوصيل',
        'Order Details': 'تفاصيل الطلب',
        'Cancel Order': 'إلغاء الطلب',
        'Shipment Address': "عنوان الشحن",
        'District': 'الحى',
        'About Us': 'عن هاى كيدز',
        'terms and conditions': 'الشروط والاحكام',
        'Details':'التفاصيل',
        'Related Products':'منتجات ذات صلة',
        'Add a comment':'أضف ملاحظة لنا',
        'Example: add a package':'مثال: أضف التغليف',
        'Order Status':'حالة الطلب',
        'Being Prepared':'تحت التجهيز',
        'Packaging Choice':'خيار التغليف',
        'Not Found':'لا يوجد',
        'Payment Method':'طريقة الدفع',
        'Submit Order':'إتمام الطلب',
        'Payment Information':'معلومات الدفع',
        'Confirm Payment':'إتمام الدفع',
        "advanced search": "تصفية البحث",
        'age': "العمر",
        'gender': 'الجنس',
        'price': 'السعر',
        'cancel filter': 'إلغاء الفلتر',
        'character': "الشخصية",
        'option': "خيار",
        'Not Available Info': 'لا يوجد',
        'Privacy Policy':'سياسة الخصوصية',
        'Delivery info':'معلومات الشحن',
        'Branches List' :'قائمة الفروع',
        'Branches on Map' :'الفروع علي الخريطة',
        'total':'الاجمالى',
        'Notes':'ملاحظات',
        'SAR':'ر.س',
        'Confirm Cancel':'تأكيد إلغاء',
        'Confirm Delete':'تأكيد الحذف',
        'No items found':' لا يوجد',
        'Are you sure to delete':'هل متأكد من الحذف ؟',
        'Are you sure to cancel this order?':'هل متأكد من إلغاء هذاالطلب؟',
        'Cancel':'إلغاء',
        'Confirm':'تأكيد',
        'An_Error_Occured':'حدث خطأ,, حاول مرة أخرى',
        'about us content': {
            "_1": "- هاي كيدز أول سوبرماركت يعتني بالطفل في المملكة العربية السعودية, استغرق تكوين فكرة و هوية المشروع مايقارب الـ 17 شهر, وبفضل الله تم إطلاق اول فروع سلسة هاي كيدز في عام 2012 .",
            "_2": "- شعارنا هو أطفالنا نجوم مفعمين بالحيوية والنشاط والمرح, ولنحقق لكم ذلك حرصنا على تقديم كل ماهو جديد ورائع في عالم الألعــاب والحلويات.",
            "_3": "- هدفنا ان نكون الشركة الأولى في ترفيه حياة الأطفال, وخلق علامة تجارية محلية بمواصفات عالمية.",
            "_4": "- يقوم سوبرماركت Hi Kids على 3 أقسام:",
            "_5": "1- قسم الالعاب و المنتجات الترفيهية والتعليمية التي من شأنها دعم المهارات الحركية و الحسية والأدراكية وتنشيط الذهـــن والأبتعاد قـــدر الأمكان عن الألعاب الألكترونية التي تقلل من الحركة.",
            "_6": "2- قسم الأطعمة والحلويات حيث نقدم فيه نخبة مختارة من أحدث المنتجات بالأضافة للمنتجات الكلاسيكية مع الابتعاد عن بعض المنـــتجات الضارة كالمشروبات الغازية.",
            "_7": "3- قسم منتجات العناية بالأم و صيدلية الطفل والتي تم اختيارها بعناية.",
        },
        'privacy policy': {
            "_1": 'الخصوصية وبيان سريّة المعلومات: نحن على علم بمسؤوليتنا تجاه حماية معلوماتك الشخصية ونأخذ هذا الأمر بجدية تامة. ونحن نعتقد أن معلوماتك الشخصية هي واحدة من أهم الموراد لدينا. نقدر مخاوفكم واهتمامكم بشأن خصوصية بياناتكم على شبكة الإنترنت. فجميع المعلومات الي تقدمها لنا هي بيانات محمية ولا يقوم بالاطلاع عليها إلا للأشخاص المخولين لذلك بموجب عملهم وفقاً لبنود حماية الخصوصية. لقد تم إعداد هذه السياسة لمساعدتكم في تفهم طبيعة البيانات التي نقوم بتجميعها منكم عند زيارتكم لموقعنا على شبكة الانترنت وكيفية تعاملنا مع هذه البيانات الشخصية.',
            "_2": 'التصفح : لم نقم بتصميم هذا الموقع من أجل تجميع بياناتك الشخصية من جهاز الكمبيوتر الخاص بك أثناء تصفحك لهذا الموقع, وإنما سيتم فقط استخدام البيانات المقدمة من قبلك بمعرفتك ومحض إرادتك.',
            "_3": 'عنوان بروتوكول شبكة الإنترنت (IP) : في أي وقت تزور فيه اي موقع انترنت بما فيها هذا الموقع , سيقوم السيرفر المضيف بتسجيل عنوان بروتوكول شبكة الإنترنت (IP) الخاص بك , تاريخ ووقت الزيارة ونوع متصفح الإنترنت الذي تستخدمه والعنوان URL الخاص بأي موقع من مواقع الإنترنت التي تقوم بإحالتك إلى الى هذا الموقع على الشبكة.',
            "_4": 'إفشاء المعلومات : سنحافظ في كافة الأوقات على خصوصية وسرية كافة البيانات الشخصية التي نتحصل عليها. ولن يتم إفشاء هذه المعلومات إلا إذا كان ذلك مطلوباً بموجب أي قانون أو عندما نعتقد بحسن نية أن مثل هذا الإجراء سيكون مطلوباً أو مرغوباً فيه للتمشي مع القانون , أو للدفاع عن أو حماية حقوق الملكية الخاصة بهذا الموقع أو الجهات المستفيدة منه.',
            "_5": 'البيانات اللازمة لتنفيذ المعاملات المطلوبة من قبلك: عندما نحتاج إلى أية بيانات خاصة بك , فإننا سنطلب منك تقديمها بمحض إرادتك. حيث ستساعدنا هذه المعلومات في الاتصال بك وتنفيذ طلباتك حيثما كان ذلك ممكنناً. لن يتم اطلاقاً بيع البيانات المقدمة من قبلك إلى أي طرف ثال بغرض تسويقها لمصلحته الخاصة دون الحصول على موافقتك المسبقة والمكتوبة ما لم يتم ذلك على أساس أنها ضمن بيانات جماعية تستخدم للأغراض الإحصائية والأبحاث دون اشتمالها على أية بيانات من الممكن استخدامها للتعريف بك.',
            "_6": 'عند الاتصال بنا : سيتم التعامل مع كافة البيانات المقدمة من قبلك على أساس أنها سرية . تتطلب النماذج التي يتم تقديمها مباشرة على الشبكة تقديم البيانات التي ستساعدنا في تحسين موقعنا.سيتم استخدام البيانات التي يتم تقديمها من قبلك في الرد على كافة استفساراتك , ملاحظاتك , أو طلباتك من قبل هذا الموقع أو أيا من المواقع التابعة له .',
            "_7": 'إفشاء المعلومات لأي طرف ثالث : لن نقوم ببيع , المتاجرة , تأجير , أو إفشاء أية معلومات لمصلحة أي طرف ثالث خارج هذا الموقع, أو المواقع التابعة له.وسيتم الكشف عن المعلومات فقط في حالة صدور أمر بذلك من قبل أي سلطة قضائية أو تنظيمية.',
            "_8": 'التعديلات على سياسة سرية وخصوصية المعلومات : نحتفظ بالحق في تعديل بنود وشروط سياسة سرية وخصوصية المعلومات إن لزم الأمر ومتى كان ذلك ملائماً. سيتم تنفيذ التعديلات هنا او على صفحة سياسة الخصوصية الرئيسية وسيتم بصفة مستمرة إخطارك بالبيانات التي حصلنا عليها , وكيف سنستخدمها والجهة التي سنقوم بتزويدها بهذه البيانات.',
            "_9": 'الاتصال بنا: يمكنكم الاتصال بنا عند الحاجة من خلال الضغط على رابط اتصل بنا المتوفر في روابط موقعنا',
            "_10": 'اخيرا إن مخاوفك واهتمامك بشأن سرية وخصوصية البيانات تعتبر مسألة في غاية الأهمية بالنسبة لنا. نحن نأمل أن يتم تحقيق ذلك من خلال هذه السياسة.',
        },
        'delivery info': {
            '_1': 'مدة الشحن و التوصيل :',
            '_2': '- بالنسبه للتوصيل المحلي: داخل المملكة تستغرق مدة الشحن غالباً من 24 ساعه إلى 7ايام عمل و قيمة التوصيل 25 ريال داخل الرياض و 50 ريال لاي منطقة اخرى داخل المملكة.',
            '_3': '- بالنسبه للتوصيل الدولي: خارج المملكة فإن مدة وقيمة الشحن تختلف بحسب الدولة التي سوف يتم الشحن إليها, كل ماعليكم لمعرفة التكاليف والوقت ارسال ايميل لنا بالأصناف التي ترغبون بها و الكميات مع بياناتكم شاملة (الاسم- العنوان- رقم الجوال) وسيتم الرد عليكم بأقرب فرصة واعلامكم بطريقة الدفع المناسبة لأيصال طلبكم, الايميل لاستقبال طلباتكم من خارج المملكة:customers_service@hikids.com.sa.',
            '_4': 'ملاحظة: سوف تقوم الشركة الناقلة بالإتصال بكم لترتيب عملية استلام المنتج.'
        },
        'pay upon delivery':'الدفع عند الاستلام(في الرياض فقط)',
        'Bank transfer':'حوالة بنكية',
        'Credit Card':'بطاقة ائتمان(فيزا، ماستر كارد)',
        'Money Account':'حساب مدي',
        'SADAD':'سداد',
        'Pickup from store':'الإستلام من الفرع(في الرياض فقط)',
        'Order Created Successfully':'تم عمل الطلب بنجاح',
        'Help':'مساعدة',
        'canceled':'تم الغاء',
        'closed':'مغلق',
        'completed':'مكتمل',
        'onhold':'في الانتظار',
        'pending':'قيد الانتظار',
        'pending payPal':'قيد الانتظار PayPal',
        'pending_payPal':'قيد الانتظار PayPal',
        'pending payment':'قيد الانتظار الدفع',
        'pending_payment':'قيد الانتظار الدفع',
        'processing':'تحت التجهيز',
        'payment review':'مراجعة الدفع',
        'payment_review':'مراجعة الدفع',
        'payfort failed':'Payfort failed',
        'payfort_failed':'Payfort failed',
        'payfort_fort_new':'طلب جديد مدفوع',
        'paypal canceled reversed':'PayPal Canceled Reversal',
        'paypal_canceled_reversed':'PayPal Canceled Reversal',
        'payfort_fort_cc': 'بطاقة ائتمان',
        'paypal reversed':'PayPal Reversed',
        'paypal_reversed':'PayPal Reversed',
        'suspected_fraud':'Suspected Fraud',
        'complete':'مكتمل',
        'Region':'المنطقة',
        'cashondelivery':'الدفع عند الاستلام',
        'ContactAddress':'العنوان: الرياض العليا مول لوكاليزر',
        'Registered Successfully':'تم التسجيل بنجاح',
        'Added to cart':'تم الإضافة إلي السلة',
        'Added to wishlist':'تم الإضافة إلي المفضلة',
        'Signed out successfully':'تم الخروج بنجاح',
        'Extra Charges': 'هذا المنتج به شحن إضافي خارج الرياض بقيمة: ',
        'IBAN number':'رقم الايبان: SA18 8000 0504 6080 1003 1954',
        'Account number':'حساب رقم: 504608010031954',
        'After bank transfer': 'الرجاء بعد التحويل إرفاق صورة من الحوالة على الواتساب علي رقم :0501217999',
        'Extra Taxes': 'مع وجود خاصية رسوم اضافية لبعض القطع الي تتجاوز وزن معين',
        'We will communicate with you for details':'ارسل طلباتك عبر الايميل(sales@yourcompany.com) و سيتم التواصل معكم للتفاصيل',
        'With option for free delivery inside Riyadh only':'(بداخل الرياض فقط)مع وجود خاصية توصيل مجاني اذا وصل الحساب لقيمة معينة يتم التحكم فيها من قبلنا او قبلكم',
        'banktransfer':'حوالة بنكية',
        'payfort_fort_sadad':'سداد',
        'Item Name':'اسم المنتج',
        'Mash`al ebn Abd-elAziz, besides Al-Danoob ':'الأمير مشعل بن عبدالعزيز، بجانب الدانوب',
        'Waseel Center, Khalid Ibn Al Walid Street, Al Hamra, 13216': 'تقاطع شارع خالد بن الوليد مع الملك عبدالله في (الوصيل سنتر)',
        '7004 King Abdul Aziz Branch Rd, King Fahd, 4500':'طريق الملك عبدالعزيز الفرعي، الملك فهد, الرياض',
        'King Abdullah Rd, King Abdullah, Riyadh 12451, Saudi Arabia':'طريق الملك عبدالله، الملك عبدالله، الرياض 12451',
        'Riyadh, Tahlia, Localizer Mall':'لوكالايزر مول-شارع التحلية-الرياض',
        'Watsapp:': 'واتساب:',
        'Unifed No:':'الرقم الموحد:',
        'Our Dear Customers':'عملاؤنا الكرام تسعدنا خدمتكم عبر الطرق التالية:',
        'Email:':'الإيميل:',
        'Cancel Payment':'الغاء عملية الدفع',
        ' Are you sure to cancel payment?':'هل متأكد من الغاء الدفع؟',
        'Product isnot available':'قد يكون المنتج المطلوب غير متاح جرب البحث  بكلمات أخرى أو تواصل معنا واتساب للمساعدة :',
        'Categories arenot available': 'لا يوجد أقسام فرعية متاحة حاليا',
        'Cart is empty': 'السلة فارغة'
    }
};

export default Languages
