export const SET_PLACES = "SET_PLACES";
export const REMOVE_PLACE = "REMOVE_PLACE";

export const SAVE_NEW_PASSWORD = "SAVE_NEW_PASSWORD";

export const UI_START_LOADING = "UI_START_LOADING";
export const UI_STOP_LOADING = "UI_STOP_LOADING";

export const AUTH_SET_TOKEN = "AUTH_SET_TOKEN";
export const AUTH_REMOVE_TOKEN = "AUTH_REMOVE_TOKEN";


export const USER_LOGGED_IN = "USER_LOGGED_IN";
export const USER_LOGGED_OUT = "USER_LOGGED_OUT";
export const UI_SELECTED_NAV = "UI_SELECTED_NAV";
export const AFTER_REGISTERATION = "AFTER_REGISTERATION"

export const USER_GET = "USER_GET";
export const USER_SAVE = "USER_SAVE";
export const USER_IS_LOGGED_IN = "USER_IS_LOGGED_IN";
export const USER_UPDATE = "USER_UPDATE";
export const USER_UPDATED = "USER_UPDATED";
export const All_USERS = "All_USERS";
export const ADMIN_LOGGED_IN = "ADMIN_LOGGED_IN";
export const INCREASE_FOLLOWINGS_COUNT = "INCREASE_FOLLOWINGS_COUNT";
export const DECREASE_FOLLOWINGS_COUNT = "DECREASE_FOLLOWINGS_COUNT"
export const GET_ACCOUNT_SUGGESTIONS = "GET_ACCOUNT_SUGGESTIONS";

export const GET_USER_SUMMARY = "GET_USER_SUMMARY";
export const USER_RESET = "USER_RESET";
export const GET_ALL_VOLUNTEERS = "GET_ALL_VOLUNTEERS";


export const GO_BACK = "GO_BACK";

export const News_SAVE = "News_SAVE";
export const News_GET = "News_GET";

export const SPONSORS_GET = "SPONSORS_GET";

export const CONSULTATION_SAVE = "CONSULTATION_SAVE";
export const CONSULTATIONS_GET = "CONSULTATIONS_GET";


export const NOTIFICATION_ADD = "NOTIFICATION_ADD";
export const NOTIFICATIONS_LIST = "NOTIFICATIONS_LIST";
export const NOTIFICATION_REMOVE = "NOTIFICATION_REMOVE";
export const NOTIFICATION_UPDATE = "NOTIFICATION_UPDATE";

export const SERVICE_ITEMS_SAVE = "SERVICE_ITEMS_SAVE";

export const SERVICES_SAVE = "SERVICES_SAVE";

export const OFFERS_SAVE = "OFFERS_SAVE";

export const TASK_LIST = "TASK_LIST";
export const TASK_ADD = "TASK_ADD";
export const TASK_UPDATE = "TASK_UPDATE";
export const TASK_REMOVE = "TASK_REMOVE";
export const UPDATE_MARKED_DATES = "UPDATE_MARKED_DATES";

export const MY_ORDERS = "MY_ORDERS";
export const SAVE_ORDER = "SAVE_ORDER";
export const ADD_ORDER = "ADD_ORDER"

export const CLEAR_USER_FILTER = "CLEAR_USER_FILTER";
export const SET_USER_TEXT = "SET_USER_TEXT";
export const SET_USER_TYPE = "SET_USER_TYPE";
export const SET_USER_ID = "SET_USER_ID"

export const SEARCH_CASES_LIST = "SEARCH_CASES_LIST";
export const SET_CASE_TEXT = "SET_CASE_TEXT";
export const SET_CASE_STATUS = "SET_CASE_STATUS";
export const ADMIN_ALL_CASES = "ADMIN_ALL_CASES";
export const SET_CASE_NOT_STATUS = "SET_CASE_NOT_STATUS";
export const SET_CASE_STATUSES = "SET_CASE_STATUSES";
export const CLEAR_CASE_FILTER = "CLEAR_CASE_FILTER";
export const VOLUNTEER_ALL_CASES = "VOLUNTEER_ALL_CASES";
export const Donor_CASES = "Donor_CASES";

export const CASES_LIMIT_LIST = "CASES_LIMIT_LIST";
export const ALL_CASES_LIST = "ALL_CASES_LIST";
export const MY_CASES_LIST = "MY_CASES_LIST";
export const GET_VOLUNTEER_CASES = "GET_VOLUNTEER_CASES";
export const CATEGORY_CASES = "CATEGORY_CASES";
export const GET_CASE = "GET_CASE";
export const GET_DONOR_CASES = "GET_DONOR_CASES";

export const CATEGORIES_LIMIT_LIST = "CATEGORIES_LIMIT_LIST";
export const ALL_CATEGORIES_LIST = "ALL_CATEGORIES_LIST";
export const ALL_CATEGORIES_FOR_DROPDOWN = "ALL_CATEGORIES_FOR_DROPDOWN";
export const GET_CATEGORY_STATISTICS = "GET_CATEGORY_STATISTICS";
export const SAVE_NEW_CATEGORY = "SAVE_NEW_CATEGORY";

export const ALL_CAMPAIGNS_LIST = "ALL_CAMPAIGNS_LIST";
export const CAMPAIGNS_LIMIT_LIST = "CAMPAIGNS_LIMIT_LIST";

export const GET_MESSAGES_HISTORY = "GET_MESSAGES_HISTORY";
export const SAVE_MESSAGES = "SAVE_MESSAGES";
export const GET_CHAT = "GET_CHAT";
export const GET_CASE_CHATS = "GET_CASE_CHATS";
export const CLEAR_CHAT = "CLEAR_CHAT";
export const GET_MY_CHATS = "GET_MY_CHATS";
export const UPDATE_CASE_CHAT = "UPDATE_CASE_CHAT";
export const MESSAGES_COUNT = "MESSAGES_COUNT"

export const ALL_NOTIFICATIONS_LIST = "ALL_NOTIFICATIONS_LIST";
export const NOTIFICATIONS_COUNT = "NOTIFICATIONS_COUNT";
export const DELETE_NOTIFICATION = "DELETE_NOTIFICATION";
export const GET_GENERAL_STATISTICS = "GET_GENERAL_STATISTICS";
export const UPDATE_SEEN_NOTIFICATION = "UPDATE_SEEN_NOTIFICATION";
export const GET_DONATIONS = "GET_DONATIONS";
export const GET_DONATIONS_AMOUNTS = "GET_DONATIONS_AMOUNTS";

export const PRODUCTS_LIMIT_LIST = "PRODUCTS_LIMIT_LIST";
export const ALL_PRODUCTS = "ALL_PRODUCTS";
export const NEW_ARRIVALS = "NEW_ARRIVALS";
export const GET_DESIGNER_PRODUCTS = "GET_DESIGNER_PRODUCTS";
export const GET_SALE_PRODUCTS = "GET_SALE_PRODUCTS";

export const GET_BANNER = "GET_BANNER";
export const GET_SUGGESTION_USERS = "GET_SUGGESTION_USERS";
export const ALL_COUNTRIES = "ALL_COUNTRIES";
export const ALL_CITIES = "ALL_CITIES";
export const LANGUAGES = "LANGUAGES";
export const GET_DELIVERY_METHODS = "GET_DELIVERY_METHODS";
export const GET_PAYMENT_METHODS = "GET_PAYMENT_METHODS";

export const GET_USER_LIKED = "GET_USER_LIKED";
export const GET_MY_LIKED = "GET_MY_LIKED";
export const GET_USER_LIKED_PRODUCTS = "GET_USER_LIKED_PRODUCTS";
export const CLEAR_LIKED_FILTER = "CLEAR_LIKED_FILTER"
export const ADD_LIKED_PRODUCT = "ADD_LIKED_PRODUCT";
export const GET_WITH_LIMIT = "GET_WITH_LIMIT";

export const PRODUCT_PRICE_FILTER = "PRODUCT_PRICE_FILTER"
export const PRODUCT_DATE_FILTER = "PRODUCT_DATE_FILTER"
export const PRODUCT_CATEGORY_FILTER = "PRODUCT_CATEGORY_FILTER"
export const PRODUCT_TYPE_FILTER = "PRODUCT_TYPE_FILTER"
export const PRODUCT_BRAND_FILTER = "PRODUCT_BRAND_FILTER"
export const CLEAR_PRODUCT_FILTER = "CLEAR_PRODUCT_FILTER"
export const PRODUCT_RANGE_FILTER = "PRODUCT_RANGE_FILTER"
export const PRODUCT_COLOR_FILTER = "PRODUCT_COLOR_FILTER"
export const PRODUCT_DESIGNER_FILTER = "PRODUCT_DESIGNER_FILTER"
export const PRODUCT_IS_IN_SALE_FILTER = "PRODUCT_IS_IN_SALE_FILTER"
export const PRODUCT_ID_FILTER = "PRODUCT_ID_FILTER"

export const ALL_TYPES_LIST = "ALL_TYPES_LIST";
export const TYPES_DROP_DOWN = "TYPES_DROP_DOWN"

export const ALL_BRANDS_FOR_DROPDOWN = "ALL_BRANDS_FOR_DROPDOWN";
export const ALL_BRANDS = "ALL_BRANDS";
export const SEARCH_LIST = "SEARCH_LIST";

export const GET_FOLLOWINGS = "GET_FOLLOWINGS";
export const ADD_FOLLOWING = "ADD_FOLLOWING";
export const GET_FOLLOWING_COUNT = "GET_FOLLOWING_COUNT";
export const ClEAR_LIST = "ClEAR_LIST"

export const GET_USERS_LIKED_PRODUCT = "GET_USERS_LIKED_PRODUCT";

export const GET_LAST_LIKED = "GET_LAST_LIKED"

export const GET_PRODUCT_LIKES = "GET_PRODUCT_LIKES"

export const GET_RECOMMENDED = "GET_RECOMMENDED"

export const GET_USER_PURCHASES = "GET_USER_PURCHASES";
export const GET_LAST_PURCHASE = "GET_LAST_PURCHASE"

export const GET_BAG_ITEMS = "GET_BAG_ITEMS";
export const ADD_TO_BAG = "ADD_TO_BAG";
export const UPDATE_BAG = "UPDATE_BAG";

export const GET_COMMENTS = "GET_COMMENTS";
export const ADD_COMMENT = "ADD_COMMENT"


export const FOODS_LIMIT_LIST = "FOODS_LIMIT_LIST";

export const PHYSICAL_LIMIT_LIST = "PHYSICAL_LIMIT_LIST";

export const PAGE_CHANGED = "PAGE_CHANGED";
export const RESET_PAGE = "RESET_PAGE";
export const INCREMENT_PAGE = "RESET_PAGE";